# Generated by Django 6.0.5 on 2026-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_cover_image_url_blogpost_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Optional external blog cover image URL. Used if no local image is uploaded.'),
        ),
    ]
