# Generated by Django 6.0.5 on 2026-05-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Private notes for yourself. Not visible to the sender.'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('general', 'General Message'), ('job_opportunity', 'Job Opportunity'), ('hire_me', 'Hire Me Inquiry'), ('freelance_project', 'Freelance / Project Work'), ('collaboration', 'Collaboration')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_message',
            field=models.TextField(blank=True, help_text='Draft your reply here. This is not emailed automatically yet.'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='ai_reply_suggestion',
            field=models.TextField(blank=True, help_text='Future AI-generated reply suggestion. Not sent automatically.'),
        ),
    ]
