# Generated by Django 6.0.5 on 2026-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL. Used if no local image is uploaded.'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external project image URL. Used if no local image is uploaded.'),
        ),
    ]
