# Generated by Django 6.0.5 on 2026-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_profile_image_url_project_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('service', 'Areas I Can Help With'), ('focus', 'Best Fit Opportunities')], default='service', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='about_secondary',
            field=models.TextField(blank=True, help_text='Second paragraph shown in the About section.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='architecture_description',
            field=models.TextField(blank=True, help_text='Description shown in the Architecture card on the homepage.'),
        ),
    ]
