# Generated by Django 6.0.5 on 2026-06-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_service_profile_about_secondary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='points',
            field=models.TextField(blank=True, default='', help_text='Enter each point on a new line. Each line becomes one bullet/tag.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('service', 'Areas I Can Help With'), ('focus', 'Best Fit Opportunities')], help_text='Only one record per category.', max_length=20, unique=True),
        ),
    ]
