# Generated by Django 6.0.5 on 2026-06-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_service_options_remove_service_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Role label that gets typed out, e.g. 'Cloud & DevOps Engineer'", max_length=200)),
                ('icon', models.CharField(choices=[('aws', 'AWS'), ('docker', 'Docker'), ('python', 'Python'), ('linux', 'Linux'), ('devops', 'DevOps / Gear'), ('backend', 'Backend / Server'), ('cloud', 'Cloud'), ('automation', 'Automation / Robot'), ('security', 'Security / Shield'), ('database', 'Database'), ('code', 'Code / Dev')], default='code', help_text='Icon shown alongside the typed text.', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
