# Generated by Django 6.0.5 on 2026-06-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_secondary',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, help_text='Text shown in the About Me section on the homepage. Separate from bio.'),
        ),
    ]
