# Generated by Django 6.0.5 on 2026-06-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_profile_about_secondary_profile_about_me'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['display_order', 'category']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='items',
            field=models.TextField(blank=True, default='', help_text='Enter each skill on a new line. e.g:\nAWS EC2\nS3\nLambda'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('cloud', 'Cloud'), ('devops', 'DevOps & CI/CD'), ('backend', 'Backend'), ('database', 'Databases'), ('security', 'Security'), ('networking', 'Networking'), ('programming', 'Programming'), ('tools', 'Tools')], help_text='One record per category.', max_length=50, unique=True),
        ),
    ]
