# Generated by Django 6.0.5 on 2026-06-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_skill_options_remove_skill_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="The figure to show, e.g. '5+', '2 yrs', 'AWS'.", max_length=20)),
                ('label', models.CharField(help_text="What it counts, e.g. 'Projects', 'Certifications'.", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
