# Generated by Django 6.0.5 on 2026-06-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
    ]
