# Generated by Django 6.0.5 on 2026-06-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_profile_instagram_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Involvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Your role, e.g. 'Teaching Fellow'.", max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('period', models.CharField(blank=True, help_text="Free text, e.g. 'Dec 2022' or 'Aug 2020 – Apr 2021'.", max_length=100)),
                ('description', models.TextField(blank=True, help_text='One point per line — each line renders as a bullet.')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
